.if n.ad l
.nh

.TH shellm-install-requirements 1 "2018-08-29" "Shellman 0.2.2" "User Commands"

.SH "NAME"
shellm-install-requirements \- Install the listed requirements for the given script

.SH "SYNOPSIS"
\fBshellm-install-requirements\fR \fIFILENAME\fR

.SH "OPTIONS"
.IP "\fB\-h\fR, \fB\-\-help\fR " 4
Prints this help and exit

.IP "\fB\-m\fR, \fB\-\-missing\fR " 4
Try to install missing requirements only
